[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "api-linter-101"
version = "1.4.0"
description = "Linter for Open API specification documents"
readme = {text = "A yaml linter for openapi documents.", content-type = "text/plain"}
authors = [
    {name = "BAUHAUS", email = "shubhushan.kattel@bahag.com"}
]
keywords = ["python", "yaml", "linter"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]
requires-python = ">=3.6"
dependencies = [
    "PyYAML",
    "python-dotenv",
    "requests",
]

[project.scripts]
linting = "linter.linter:main"
