[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "api-linter-101"
version = "1.2.0"
description = "Linter for Open API specification documents"
readme = "README.md"
authors = [
    {name = "BAUHAUS", email = "shubhushan.kattel@bahag.com"}
]
keywords = ["python", "yaml", "linter"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]
requires-python = ">=3.6"
dependencies = [
    "PyYAML",
    "python-dotenv",
    "requests",
]

[project.scripts]
linting = "linter.linter:main"