name: CI for docker images

on:
  pull_request:
    types:
      - opened
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BIGQUERY_API_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_API_SERVICE_ACCOUNT_JSON }}
  SWAGGERHUB_API_KEY: ${{ secrets.SWAGGER_HUB_KEY }}

jobs:
  local-dev-test-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: install packages
        run: pip3 install -r requirements.txt

      - name: Test the linter with sample yaml files in the tests/ directory
        run: ./test_linter.sh

      - name: Test linter with real specification files to catch bugs
        if: ${{ success() }}
        run: python3 test-yaml-loading.py