# create a github workflow to release package from /package to PYPI
name: Release PYPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies
      run: |
        pip install setuptools wheel twine

    - name: Build and publish
      working-directory: ./package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
  kpi-deployment-count:
    needs: [build]
    runs-on: [self-hosted, linux, x64, gke-hosted, size-xs]
    environment: kpi-deployment-count
    steps:
      - name: Deployment
        run: echo "Successful deployed to prod - $(date)"